

ansible-galaxy init --type=apb nxp-nexus-apb

Open the DockerFile and change

ansibleplaybookbundle/apb-base --> registry.redhat.io/openshift3/apb-base

-------------------------------------------------------------
Build the APB from source

cd /home/rahmed/NXP/nexus/nxp-nexus-apb

The following step is very important to do #whenever you modify the apb.yml# so it update the base64 in Dockerfile

apb bundle prepare

oc new-build --binary=true --name nxp-nexus-apb
oc start-build --follow --from-dir . nxp-nexus-apb

add the internal OpenShift registry to our list of configured registries:

apb registry add nxp-registry --url=https://openshift.rahmed.lab.pnq2.cee.redhat.com:443 --type=local_openshift --namespaces=nxp-nexus

apb bundle list --refresh




-------------------------------------------------------------


As we are using localStorage so i need a serviceaccount, so as a required step create service account with needed privilages

oc create sa nexus
oc adm policy add-scc-to-user hostmount-anyuid -z nexus


sudo mkdir -p /ocp-data/nexus-data

sudo chown -R 1000340000:root /ocp-data/nexus-data
sudo chmod -R g+w /ocp-data/nexus-data
sudo chcon -R system_u:object_r:svirt_sandbox_file_t:s0:c18,c17 /ocp-data/nexus-data

-------------------------------------------------------------


To test your work


apb bundle provision nxp-nexus-apb --follow

Usage:
  apb bundle provision <apb-name> [flags]

Flags:
  -f, --follow                Print logs from provision pod
  -h, --help                  help for provision
  -n, --namespace string      Namespace to provision APB to
  -r, --registry string       Registry to load APB from
  -s, --sandbox-role string   ClusterRole to be applied to APB sandbox (default "edit")

Global Flags:
      --config string       configuration directory (default is $HOME/.apb)
  -k, --kubeconfig string   Path to kubeconfig to use (default is $HOME/.kube/config)
  -v, --verbose             verbose output


---
Default Cluster Role		Description	
edit  				A user that can modify most objects in a project, but does not have the power to view or modify roles or bindings.
admin				A project manager. If used in a local binding, an admin user will have rights to view any resource in the project and modify any resource in the project except for quota.

-------------------------------------------------------------

Other way is to use docker run

oc create serviceaccount apb
oc create rolebinding apb --clusterrole=admin --serviceaccount=nxp-nexus:apb

oc run nxp-nexus \
      --env="POD_NAME=apb_test" \
      --env="POD_NAMESPACE=nxp-nexus" \
      --image=docker-registry.default.svc:5000/openshift/nxp-nexus-apb \
      --restart=Never \
      --attach=true \
      --serviceaccount=apb \
      -- provision \
      -e "namespace=nxp-nexus" \
      -e "nexus_ssl=True" \
      -e "nexus_state=present" \
      -e "nexus_volume_size=1Gi" \
      -e "nexus_memory_request=1Gi" \
      -e "nexus_memory_limit=2Gi" \
      -e "nexus_cpu_request=500m" \
      -e "nexus_cpu_limit=2" \
      -e "nexus_image_tag=latest" \
      -e "nexus_admin_password=passw0rd"




ansible-playbook /opt/apb/actions/provision.yml \
  -e "namespace=nxp-nexus" \
  -e "nexus_ssl=True" \
  -e "nexus_state=present" \
  -e "nexus_volume_size=1Gi" \
  -e "nexus_memory_request=1Gi" \
  -e "nexus_memory_limit=2Gi" \
  -e "nexus_cpu_request=500m" \
  -e "nexus_cpu_limit=2" \
  -e "nexus_image_tag=latest" \
  -e "nexus_admin_password=passw0rd"
