---
# defaults file for nexus-ocp
_nexus_state: '{{ nexus_state }}'
_nexus_namespace: '{{ namespace }}'
_nexus_name: nexus3
_nexus_pod_name: '{{ _nexus_name }}-0'

_nexus_service_account: '{{ nexus_service_account }}'
_nexus_ssl: '{{ nexus_ssl }}'
_nexus_volume_size: '{{ nexus_volume_size }}'
_nexus_memory_request: '{{ nexus_memory_request }}'
_nexus_memory_limit: '{{ nexus_memory_limit }}'
_nexus_cpu_request: '{{ nexus_cpu_request }}'
_nexus_cpu_limit: '{{ nexus_cpu_limit }}'
_nexus_wait_for_init: True
#_nexus_image: docker.io/sonatype/nexus3
_nexus_image: registry.connect.redhat.com/sonatype/nexus-repository-manager
_nexus_image_tag: latest

_nexus_admin_password: admin123
_new_nexus_admin_password: '{{ nexus_admin_password }}'
_nexus_delete_default_repos: true

_nexus_repos_maven_defaults:
  blob_store: default
  strict_content_validation: true
  version_policy: release # release, snapshot or mixed
  layout_policy: strict # strict or permissive
  write_policy: allow_once # allow_once or allow

_nexus_repos_maven_proxy:
  - name: maven-central
    remote_url: https://repo1.maven.org/maven2/
    layout_policy: permissive
  - name: redhat-ga
    remote_url: https://maven.repository.redhat.com/ga/
    layout_policy: permissive
  # - name: jboss
  #   remote_url: https://repository.jboss.org/nexus/content/groups/public

_nexus_repos_maven_hosted:
  - name: releases
    version_policy: release
    write_policy: allow_once

_nexus_repos_maven_group:
  - name: maven-all-public
    member_repos:
      - maven-central
      - redhat-ga
#      - jboss

_nexus_repos_docker_defaults:
  blob_store: default
  strict_content_validation: true
  version_policy: release # release, snapshot or mixed
  layout_policy: strict # strict or permissive
  write_policy: allow_once # allow_once or allow

_nexus_repos_docker_hosted:
  - name: docker
    http_port: 5000
    v1_enabled: True

_nexus_repos_npm_defaults:
  blob_store: default
  strict_content_validation: true
  write_policy: allow_once # allow_once or allow

_nexus_repos_npm_proxy:
  - name: npm
    remote_url: https://registry.npmjs.org

_nexus_repos_npm_group: []
  # - name: npm-all
  #   member_repos:
  #     - npm-internal
  #     - npm-proxy
