---
- name: Debug old parameters
  debug:
    msg: "nexus_url: {{ nexus_url }}, script_name: {{ script_name }}, _nexus_admin_password: {{ _nexus_admin_password }}"
- name: Calling Groovy script {{ script_name }}
  uri:
    url: "{{ nexus_url }}/service/rest/v1/script/{{ script_name }}/run"
    user: admin
    password: "{{ _nexus_admin_password }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    force_basic_auth: yes
    validate_certs: no
    body: "{{ args | to_json }}"
