---
#- name: Removing previously declared Groovy script {{ item }}
  # uri:
  #   url: "{{ nexus_url }}/service/siesta/rest/v1/script/{{ item }}"
  #   user: admin
  #   password: "{{ _nexus_admin_password }}"
  #   method: DELETE
  #   force_basic_auth: yes
  #   status_code: 204,404

- name: Declaring Groovy script {{ item }}
  uri:
    url: "{{ nexus_url }}/service/rest/v1/script"
    user: admin
    password: "{{ _nexus_admin_password }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    validate_certs: no
    body:
      name: "{{ item }}"
      type: 'groovy'
      content: "{{ lookup('file', 'groovy/' + item + '.groovy') }}"
