---
# tasks file for Nexus
- name: Debug old parameters
  debug:
    msg: "_nexus_volume_size: {{ nexus_volume_size }}, _nexus_ssl: {{ nexus_ssl }}"
- name: Debug parameters things
  debug:
    msg: "_nexus_state: {{ _nexus_state }}, _nexus_service_account: {{ _nexus_service_account }}, _nexus_cpu_request: {{ _nexus_cpu_request }}, _nexus_memory_request: {{ _nexus_memory_request }}, _nexus_cpu_limit: {{ _nexus_cpu_limit }}, _nexus_memory_limit: {{ _nexus_memory_limit }},_new_nexus_admin_password: {{ _new_nexus_admin_password }}"

- name: Set Nexus Service to {{ _nexus_state }}
  k8s:
    state: "{{ _nexus_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ _nexus_name }}"
        namespace: "{{ _nexus_namespace }}"
        labels:
          app: "{{ _nexus_name }}"
      spec:
        selector:
          app: "{{ _nexus_name }}"
        ports:
        - name: "nexus-tcp"
          port: 8081
          protocol: TCP
          targetPort: 8081
        sessionAffinity: None
        type: ClusterIP

- name: Set Nexus Registry Service to {{ _nexus_state }}
  k8s:
    state: "{{ _nexus_state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ _nexus_name }}-registry"
        namespace: "{{ _nexus_namespace }}"
        labels:
          app: "{{ _nexus_name }}"
      spec:
        selector:
          app: "{{ _nexus_name }}"
        ports:
        - name: "nexus-registry-tcp"
          port: 5000
          protocol: TCP
          targetPort: 5000
        sessionAffinity: None
        type: ClusterIP

- name: Set Nexus Route to {{ _nexus_state }}
  k8s:
    state: "{{ _nexus_state }}"
    definition: "{{ lookup('template', './templates/nexus_route.j2') | from_yaml }}"
  register: nexus_route

- name: Set Nexus Registry Route to {{ _nexus_state }}
  k8s:
    state: "{{ _nexus_state }}"
    definition: "{{ lookup('template', './templates/nexus_registry_route.j2') | from_yaml }}"

- name: Pause to wait for pod to be in the system
  when:
    - _nexus_state == "present"
    - _nexus_wait_for_init|bool
  pause:
    seconds: 5

- name: Verify that the Nexus Pod is running
  when:
    - _nexus_state == "present"
    - _nexus_wait_for_init|bool
  k8s:
    api_version: v1
    kind: Pod
    name: "{{ _nexus_name }}"
    namespace: "{{ _nexus_namespace }}"
  register: nexus_pod
  until:
  - nexus_pod.result.status.phase == "Running"
  retries: 50
  delay: 30
  changed_when: false

- name: Wait for the Nexus Pod to be ready
  when:
    - _nexus_state == "present"
    - _nexus_wait_for_init|bool
  k8s:
    api_version: v1
    kind: Pod
    name: "{{ _nexus_name }}"
    namespace: "{{ _nexus_namespace }}"
  register: nexus_pod
  until:
  - nexus_pod.result.status.containerStatuses[0].ready|d(False)|bool
  retries: 50
  delay: 10
  changed_when: false

- name: Perform Initial Nexus Configuration
  include_tasks: setup.yml
  vars:
    nexus_url: "{{ 'http' if not _nexus_ssl|d(False)|bool else 'https' }}://{{ nexus_route.result.spec.host }}"
