---
# Tasks to setup Nexus the first time

# Discover admin password for 3.17+
- name: Attempt to fetch password file
  shell: "oc cp {{ _nexus_name }}:/nexus-data/admin.password /tmp/admin.password -n {{ _nexus_namespace }}"
  ignore_errors: true

- name: Check for temporary file
  stat:
    path: /tmp/admin.password
  register: password_file_result

- name: Get Admin Password for 3.17+
  when: password_file_result.stat.exists
  block:
    - name: Read file
      slurp:
        src: /tmp/admin.password
      register: admin_password
    - name: Save admin password
      set_fact:
        _nexus_admin_password: "{{ admin_password['content']|b64decode }}"
    - name: Remove temporary file
      file:
        path: /tmp/admin.password
        state: absent


# Upload all groovy scripts we will be using
- name: Declare groovy scripts
  include_tasks: declare_script.yml
  with_items:
    - update_admin_password
    - delete_repo
    - create_repo_maven_proxy
    - create_repo_maven_group
    - create_repo_maven_hosted
    - create_repo_docker_hosted
    - create_repo_npm_hosted
    - create_repo_npm_proxy
    - create_repo_npm_group
    - set_anon_access

# Delete default repos
- name: Delete default repos
  include_tasks: delete_repo.yml
  when: _nexus_delete_default_repos
  with_items:
    - maven-central
    - maven-public
    - maven-releases
    - maven-snapshots
    - nuget-group
    - nuget-hosted
    - nuget.org-proxy

- name: Create Maven Proxies
  include_tasks: create_repo_maven_proxy.yml
  with_items: "{{ nexus_repos_maven_proxy | d(_nexus_repos_maven_proxy) }}"

- name: Create Maven Hosted Repos
  include_tasks: create_repo_maven_hosted.yml
  with_items: "{{ nexus_repos_maven_hosted | d(_nexus_repos_maven_hosted) }}"

- name: Create Maven Groups
  include_tasks: create_repo_maven_group.yml
  with_items: "{{ nexus_repos_maven_group |  d(_nexus_repos_maven_group) }}"

- name: Create Docker Repos
  include_tasks: create_repo_docker_hosted.yml
  with_items: "{{ nexus_repos_docker_hosted | d(_nexus_repos_docker_hosted) }}"

- name: Create NPM Proxies
  include_tasks: create_repo_npm_proxy.yml
  with_items: "{{ nexus_repos_npm_proxy | d(_nexus_repos_npm_proxy) }}"

- name: Create NPM Groups
  include_tasks: create_repo_npm_group.yml
  with_items: "{{ nexus_repos_npm_group | d(_nexus_repos_npm_group) }}"

- name: Turn on Anonymous Access
  include_tasks: set_anon_access.yml

- name: Update Admin Password
  include_tasks: update_admin_password.yml
  when: new_nexus_admin_password is defined

- name: Change default password
  set_fact:
    _nexus_admin_password: "{{ new_nexus_admin_password }}"
  when: new_nexus_admin_password is defined

# The following will fail unless this is running as an operator
- name: Save password in custom resource status
  k8s_status:
    api_version: gpte.opentlc.com/v1alpha1
    kind: Nexus
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      admin_password: "{{ _nexus_admin_password }}"
  ignore_errors: true
