apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    nexus-pv: "true"
    type: local
  name: pv-nexus-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /ocp-data/nexus-data
  persistentVolumeReclaimPolicy: Retain
